
[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pascalw/go-alfred"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/uetchy/go-qiita"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mitchellh/gox"
  version = "0.4.0"
